apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: telegram-bot-ingress
  namespace: trading-ai
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - telegram-bot.dotland.fr
      secretName: telegram-bot-tls
  rules:
    - host: telegram-bot.dotland.fr
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: telegram-bot
                port:
                  number: 80
